### ISSUE TITLE
Add flutter install

### ISSUE THREAD

**Issue by banalg** [GeKorm/dart-windows#6]
Is it possible to add an option to install also Flutter SDK ?

Here is the current guide to install Flutter
https://github.com/flutter/flutter/wiki/Flutter-on-Windows

With the part about Flutter SDK :

> Open a fresh PowerShell or Cmd command prompt window and clone the Flutter repository with the following command:
> git clone https://github.com/flutter/flutter.git
> This creates a flutter sub-directory in the current directory.

**Comment by GeKorm** [comment]
Hi sorry for the late response and thanks for opening an issue. 

Since Flutter includes and manages the Dart SDK versions, do you think it would be better to have it as a separate installer altogether, instead of an option?

As for the implementation:  
Since `flutter doctor` seems integral to the installation process, I could make the installer download flutter and set the PATH, then launch the command line with `flutter doctor` for additional configuration.  
Ideally, I would like to make the last step optional. 

I'll look into this, thanks for the great suggestion.

**Comment by banalg** [comment]
Hello,

You're probably right, a dedicated installer should be a better solution. Because some developers will just need to use flutter without knowing what is the SDK and Chromium.

Automatically running flutter is a good idea, but is is important to show to the user what he need to improve in order to finish the installation.

Regards,
